### ISSUE TITLE
Include a funtion to obtain the current network adapter in use.

### ISSUE THREAD

**Issue by k3z0** [unosquare/raspberryio#102]
Include a function to obtain the current network adapter in use. This could be accomplished by parsing the results of the **route** command:

```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.1.0     *               255.255.255.0   U     1      0        0 eth0
link-local      *               255.255.0.0     U     1000   0        0 eth0
default         192.168.1.1     0.0.0.0         UG    0      0        0 eth0
```

The _Iface_ column in the line with destination _default_ tells you which interface is used.

[Reference](https://unix.stackexchange.com/questions/14961/how-to-find-out-which-interface-am-i-using-for-connecting-to-the-internet)

**Comment by geoperez** [comment]
@k3z0 are you going to add this?
