### ISSUE TITLE
BCM pin above 31 for CM3/3+ modules 

### ISSUE THREAD

**Issue by dobova86** [unosquare/raspberryio#103]
Hi, I'm using CM3+ module and C wiringPi lib has no problem to work with Gpio BCM pin above 31 (0..31), also using your native wiringPi project. It doesn't work with abstraction library (max pin is 31). It would be useful to extend abstraction pins definition.

**Comment by foxton33** [comment]
Hi, I too would like this as I would like to use the GPIOs 38 - 43 on the CM3.

Thanks

**Comment by paez9817** [comment]
I have the same problem with C3M+, the new versions solve this problem? I work with 0.23 version
