### ISSUE TITLE
No reason to target 4.6.2 - Target 4.6.1 instead

### ISSUE THREAD

**Issue by mariodivece** [unosquare/raspberryio#106]
**Describe the bug**
TargetFramewors is set to 4.6.2. Retarget to 4.6.1. There is no need for 4.6.2

**To Reproduce**

**Expected behavior**
Build for a minimum base version

**Comment by geoperez** [comment]
There is a reason, the compatibility with netstandard2.0.

**Comment by geoperez** [comment]
Please check the new nugets.
