### ISSUE TITLE
 System.MissingMethodException

### ISSUE THREAD

**Issue by conhoj** [unosquare/raspberryio#107]
**Describe the bug**
Missing Method Exception when attempting to run Playground

**To Reproduce**
 mono Unosquare.RaspberryIO.Playground.exe
or 
 dotnet Unosquare.RaspberryIO.Playground.dll

get the same error:-

 18:58:34.137 INF >> Starting program at 08/04/2019 18:58:33
 18:58:34.319 ERR >> [Main] Error
    $type           : System.MissingMethodException
    Message         :
        Method not found: int Unosquare.RaspberryIO.Abstractions.Native.Standard.StringToInteger(string,intptr,int)
    TargetSite      : Void Bootstrap()
    StackTrace      :
        at Unosquare.WiringPi.BootstrapWiringPi.Bootstrap () [0x00010] in <8f45db76a1d248788faaef47a92f23ac>:0
        at Unosquare.RaspberryIO.Pi.Init[T] () [0x00024] in <9c2d149f4e0240fbb3ab95b3420dc46f>:0
        at Unosquare.RaspberryIO.Playground.Program.Main () [0x00048] in <392f8207c86d4f8d893229bb64150b60>:0
    Source          : Unosquare.WiringPi
    HResult         : -2146233069
 18:58:34.902 INF >> Program finished.

**Expected behavior**

**Screenshots**

**Devices**
Raspberry version V3 B Raspbian

**Comment by geoperez** [comment]
Can you clone your repo again?

**Comment by conhoj** [comment]
Hi done that works a charm Thankyou
