### ISSUE TITLE
RetrieveWirelessNetworks retrieving wrong network security

### ISSUE THREAD

**Issue by edmundormz** [unosquare/raspberryio#11]
I wasn't able to detect the reason for this issue. When running Playground on rasp no password is required for secured networks, especially for Unosquare Mobiles.

At same time, ran "iwlist wlan0 scanning" which retrieves that network as secured.

This is a recurrent problem when using the wifi-connection assistant of AccessCore, sometimes it does not ask for password trying to connect to Unosquare WiFi

Any idea why this behaviour?

**Comment by geoperez** [comment]
Already resolved.

**Comment by edmundormz** [comment]
Good to know. Is this project still alive or already running?

Best regards to everybody at UnoLbas, miss you guys

**Comment by geoperez** [comment]
It's alive as Nestor! xD
