### ISSUE TITLE
pin access

### ISSUE THREAD

**Issue by sab0h** [unosquare/raspberryio#110]
Hey, actually after updating, i can't access to pin options like before.

Example:
http://prntscr.com/nc55fo

**Comment by k3z0** [comment]
Hi @sab0h 

Try to cast explicitly the IGpioPin to WiringPi.GpioPin:

```csharp
    var pin = (WiringPi.GpioPin)Pi.Gpio[BcmPin.Gpio24];
```

This is because, for the moment, only the implementation for WiringPi supports SoftPwm.
