### ISSUE TITLE
simple example

### ISSUE THREAD

**Issue by daveyostcom** [unosquare/raspberryio#111]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by daveyostcom** [comment]
Getting started with dotnetcore on RPi would be so much easier if the solution would include a console app project that builds and is ready to copy to RPi, along with a paragraph or two specifically about the specifics of the specific example. ;-)  It can just blink a light. Anything that goes the whole way there.

Thanks

**Comment by k3z0** [comment]
Hi @daveyostcom,

We appreciate that you take your time to make suggestions to the project's readme. If you already had modified the readme with some improvements, please submit your PR so we can review your suggestions to add it to the project.

Thanks.
