### ISSUE TITLE
Playground example for inputs and buttons?

### ISSUE THREAD

**Issue by daveyostcom** [unosquare/raspberryio#112]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by daveyostcom** [comment]
Hi.  I can't see anything that helps with input from the pins. I'm trying to get input from the capacitive touch inputs on the [Explorer HAT Pro](https://shop.pimoroni.com/products/explorer-hat).

Thanks

**Comment by k3z0** [comment]
Hi @daveyostcom 

We don´t have an "Explorer Hat Pro" for performing tests, but in its [technical reference page](https://github.com/pimoroni/explorer-hat/blob/master/documentation/Technical-reference.md), they mention that you must use I2C to communicate with the hat. In RaspberryIO's readme, you can found examples of [I2C](https://github.com/unosquare/raspberryio#i2c-to-connect-ics) communication.
