### ISSUE TITLE
GPIO Pin Interrupts: which pin? RegisterInterruptCallback overload throws exception.

### ISSUE THREAD

**Issue by jifka** [unosquare/raspberryio#114]
I can register an interrupt using a parameter-less callback function. But if I use the provided overload that supposedly returns the pin number and current value, an exception is thrown indicating that WiringPi does not support it.

This is using the latest official release of raspberryio.

**Comment by k3z0** [comment]
Hi @jifka 

In fact, WiringPi does only support parameterless callback, the only one that actually supports parameters in the callback function is PiGpio. So, that overload is only supported when you use the PiGpio implementation.

**Comment by jifka** [comment]
Thanks, and apologies for asking a simple question - how would I use the PiGpio implementation? Is this not yet released?

**Comment by k3z0** [comment]
We are still working in the PiGpio implementation. For the moment you only will be able to use the parameterless callback function provides by WiringPi.

**Comment by geoperez** [comment]
Is this issue WIP?
