### ISSUE TITLE
How can i implement Dht11 class in my project?

### ISSUE THREAD

**Issue by dinoToribio** [unosquare/raspberryio#140]
can anyone tell how to use the Dht11 Class??

**Comment by Serk352** [comment]
Hi @dinoToribio , the easiest way to do it is using the class DhtSensor and his static method Create, inside the playground project there is a function called TestTempSensor, here you can see a working implementation of a Dht11 sensor.

Example:
https://github.com/unosquare/raspberryio/blob/master/src/Unosquare.RaspberryIO.Playground/Peripherals/Peripherals.TempHum.cs

**Comment by dinoToribio** [comment]
Thank you Serk352.

**Comment by dinoToribio** [comment]
By the way @Serk352, can you tell me the more details step by step on how i can run the project in a raspberry pi. And i use windows C# form application to use the class. Is that allowed? Sorry,  i asked a lot because i am just beginner in this kind of field.

Thank you in advance @Serk352.

**Comment by Serk352** [comment]
Hi @dinoToribio ,
To run the project on the RaspberryPi you need to deploy the files to a local folder, you can accomplish this using our tool [sshdeploy](https://github.com/unosquare/sshdeploy). There is an [example ](https://github.com/unosquare/raspberryio#run-the-app-on-the-raspberry) in the RaspberryIO documentation.
About using winforms, apparently Net Core 3 will have support for it, but only on Windows. [More Info](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0). Running on Linux (Raspbian) it is only possible to use console apps.

**Comment by Serk352** [comment]
Can we close this ticket?

**Comment by k3z0** [comment]
Hi @dinoToribio 

Maybe you could use Winforms on Linux if you run your app using Mono, more info [here](https://www.mono-project.com/docs/gui/winforms/). Unfortunately, this is out of the scope of RaspberryIO.

**Comment by dinoToribio** [comment]
I understand now. Thank you very much everyone.
