### ISSUE TITLE
LED Strip Misssing

### ISSUE THREAD

**Issue by vbisbest** [unosquare/raspberryio#149]
I cannot seem to find the LED Strip (APA102) class under peripherals.  I am using the nuget package directly from nuget (not building myself).   Thanks!

**Comment by geoperez** [comment]
What target framework are you using?

**Comment by vbisbest** [comment]
.Net Core 2.2.  And targeting linux-arm (for Raspberry Pi 3B+)

**Comment by geoperez** [comment]
Please upgrade to nuget version 0.5.0.

**Comment by vbisbest** [comment]
Ok, the class is there now, but I cannot init PI.  Per your docs:

Pi.Init<BootstrapWiringPi>();

BootstrapWIringPi is not a valid object.

**Comment by k3z0** [comment]
Hi @vbisbest 

Try to use [this ](https://github.com/unosquare/raspberryio#usage)init code:

```csharp
Pi.Init<BootstrapWiringPi>();
```

**Comment by vbisbest** [comment]
Ok, I was missing that nuget package.  I have all that setup and now getting this error on the Pi.Init call.

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Unosquare.Swan, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Unosquare.Swan, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null'
   at Unosquare.WiringPi.BootstrapWiringPi.Bootstrap()
   at Unosquare.RaspberryIO.Pi.Init[T]()
   at LightWall.Controllers.HomeController.Index() in C:\Users\Ray\Documents\Projects\LightWall\Controllers\HomeController.cs:line 18
   at lambda_method(Closure , Object , Object[] )

**Comment by vbisbest** [comment]
I should add, the version of swan that gets installed is 2.0.1 (seems to be looking for 1.2.4)

**Comment by geoperez** [comment]
Thanks for the heads up. WiringPi nuget was outdated. Please upgrade to version 0.5.0.

**Comment by vbisbest** [comment]
I think we are closer.  Now I get this error when I create the LED Strip.
Unable to open SPI device: No such file or directory

Here is the code I am using.  I tried SPI channel 0 and 1.
            
```
Pi.Init<BootstrapWiringPi>();
            Unosquare.RaspberryIO.Peripherals.LedStripAPA102C led = new Unosquare.RaspberryIO.Peripherals.LedStripAPA102C(10, 0, 1000000);
            led.ClearPixels();
```
And thank you very much for your prompt responses and fixes!

**Comment by vbisbest** [comment]
AHHH! Never mind.  I had to enable the SPI interface on the rpi.   Thank you again!
