### ISSUE TITLE
Documentation: Hardware PWM GPIO pins

### ISSUE THREAD

**Issue by acarlonvs** [unosquare/raspberryio#184]
**Describe the bug**
Documentation states: 
   "Note: Hardware PWM can be used only in GPIO13 and GPIO18"

**Expected behavior**
Can't GPIO 12/13/18/19 be used for hardware PWM?

**Comment by k3z0** [comment]
Hi @acarlonvs 

Actually yes, you can use GPIO pins 12/13/18/19 for Hardware PWM.

It is only a outdated part of the documentation we must fix.
