### ISSUE TITLE
I need to analog read a pin, but it seems Read() only returns boolean

### ISSUE THREAD

**Issue by HolyOne** [unosquare/raspberryio#186]

**Comment by k3z0** [comment]
The Raspberry Pi’s GPIO pins are digital pins, so you can only set outputs to high or low, or read inputs as high or low. However, using an ADC chip (Analogue-to-Digital converter), you can read the value of analog input devices.

[Here](https://projects.raspberrypi.org/en/projects/physical-computing/14) you can find a sample project.
