### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by NICKHAMAN** [unosquare/raspberryio#202]
I can't find a method to set the I2C bus ID.  I'm using a compute module and both i2c-0 and i2c-1 are available.

**Comment by k3z0** [comment]
Hi @NICKHAMAN 

WiringPi does not allow to, explicitly, select an I2C bus. According to the source code, it uses **_i2c-1_** for "_everything from the B revision 2 to the B+, the Pi v2, v3, zero and CM's_".
