### ISSUE TITLE
WiringPi does only support a simple interrupt callback that has no parameters

### ISSUE THREAD

**Issue by logicethos** [unosquare/raspberryio#204]
**Describe the bug**

After I do 
`Pi.Init<BootstrapWiringPi>(); `
I get this error
`WiringPi does only support a simple interrupt callback that has no parameters.`

**To Reproduce**
I copied /usr/lib/libwiringPi.so.2.50 to my app directory.
I had to do this to overcome this issue https://github.com/unosquare/raspberryio/issues/62

**Devices**
Pi 2 Model B
Raspbian GNU/Linux 9.8 (stretch)
Unosquare.Raspberry.IO : 0.27.0
Unosquare.WiringPi: 0.5.0

**Comment by k3z0** [comment]
Hi @logicethos ,

Actually, that message is not an error, That message is indicating that WiringPi does not support a callback with parameters as interrupt callback, you must call the overload with the Action that does not take any parameter: `RegisterInterruptCallback(EdgeDetection edgeDetection, Action callback)`.

**Comment by logicethos** [comment]
Ah, understood. Thank you.
