### ISSUE TITLE
sudo nuget install Unosquare.Raspberry.IO dont work anymore? 

### ISSUE THREAD

**Issue by JanZumdick** [unosquare/raspberryio#217]
sudo nuget install Unosquare.Raspberry.IO dont work anymore? 
"An error occurred while retrieving package metadata for 'Unosquare.Raspberry.IO' from source 'nuget.org'.

 Index was outside the bounds of the array.

**Comment by JanZumdick** [comment]
![fehler](https://user-images.githubusercontent.com/58948686/95856036-b2538300-0d59-11eb-86b3-34993701d85a.png)

**Comment by geoperez** [comment]
It looks like an issue with the nuget client. Can you try on another computer?

**Comment by JanZumdick** [comment]
i did. 

On Raspberry it dont work (Testet on 2 Raspberry Pi 4 [kali and raspbian])
On my Windows-Computer, it work fine (Visual Studio 2019 Ent).

**Comment by JanZumdick** [comment]
![sameerror](https://user-images.githubusercontent.com/58948686/95874642-6280b600-0d71-11eb-9c0c-e4f1b4867ac6.png)
Still the same
