### ISSUE TITLE
How to Use ADS1115 I2C Analog-to-Digital Converter devices

### ISSUE THREAD

**Issue by DevilK89** [unosquare/raspberryio#231]
Good afternoon,

I would like to know if you have any example of communication with the ADS1115 card, as I am not able to communicate with the card, currently it appears the error id 72 could not be registered with the I2C bus.

Thank you for now.

**Comment by multisys** [comment]
Hi, I am having the same problem.

**Comment by multisys** [comment]
**DevilK89** please put your code.

**Comment by DerpyDoom** [comment]
This is the way I'm using the ADS1115:

```
var mainADC = new Unosquare.RaspberryIO.Peripherals.ADS1115();

while (true)
{
    Console.WriteLine("Raw Voltage: " + mainADC.ReadChannel(0x0)); //Read Channel 1
    Console.WriteLine("Raw Voltage: " + mainADC.ReadChannel(0x1)); //Read Channel 2
    Console.WriteLine("Raw Voltage: " + mainADC.ReadChannel(0x2)); //Read Channel 3
    Console.WriteLine("Raw Voltage: " + mainADC.ReadChannel(0x3)); //Read Channel 4
    Thread.Sleep(1000);
}
```

**Comment by geoperez** [comment]
We are looking for a new maintainer, apply at https://adoptoposs.org/p/9f5b74b9-04f2-42b6-891f-c5294c9ef1c5
