### ISSUE TITLE
Support the I2C HD44780 (1604 LC-Display)

### ISSUE THREAD

**Issue by DerpyDoom** [unosquare/raspberryio#232]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd love to have support for the I2C LCD 1604 Display. (Controller HD44780)

**Describe alternatives you've considered**
None

**Additional context**
None (at this moment)

**Comment by geoperez** [comment]
We are looking for a new maintainer, apply at https://adoptoposs.org/p/9f5b74b9-04f2-42b6-891f-c5294c9ef1c5
