### ISSUE TITLE
The type or namespace name 'Gpio' does not exist in the namespace 'Unosquare.RaspberryIO' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by johnstaveley** [unosquare/raspberryio#233]
I am trying to write the following code:
using Unosquare.RaspberryIO;
using Unosquare.RaspberryIO.Gpio;

It fails on the second line with the error message:

The type or namespace name 'Gpio' does not exist in the namespace 'Unosquare.RaspberryIO' (are you missing an assembly reference?)

I have added the following packages:

    <PackageReference Include="System.Device.Gpio" Version="1.3.0" />
    <PackageReference Include="Unosquare.Raspberry.IO" Version="0.27.1" />
    <PackageReference Include="Unosquare.WiringPi" Version="0.5.1" />

Please can you update your documentation at https://github.com/unosquare/raspberryio to indicate what I need to install to get past this error?

**Comment by geoperez** [comment]
We are looking for a new maintainer, apply at https://adoptoposs.org/p/9f5b74b9-04f2-42b6-891f-c5294c9ef1c5
