### ISSUE TITLE
Z-Wave functionality

### ISSUE THREAD

**Issue by FrankDoersam** [unosquare/raspberryio#24]
Hello,

is it possible to address a z-wave usb stick in .net core? :)

Best regards

**Comment by geoperez** [comment]
Can you explain a little bit more? Do you know any SDK or library using that hardware?

**Comment by FrankDoersam** [comment]
A reference libary witch use mono:
https://github.com/roblans/ZWave4Net

**Comment by geoperez** [comment]
I think it may run with Net Core 2. I didn't see something missing for .NET Standard libs. You may ask them if they have plans to support it.
