### ISSUE TITLE
Shutdown|Restart

### ISSUE THREAD

**Issue by FrankDoersam** [unosquare/raspberryio#25]
Hey,
i would miss an Interface to restart and shutdown the device.
Could you implement that in this fantastic library :)

Best regards
Frank

**Comment by mariodivece** [comment]
Why not use the built-in SWAN ProcessRunner? just do something like:

```csharp
var shutdownResult = await ProcessRunner.GetProcessResultAsync("halt");
var restartResult = await ProcessRunner.GetProcessResultAsync("reboot");
```

It would be certainly nice to implement these methods as:
```csharp
Pi.Reboot();
Pi.Shutdown();
```

https://github.com/unosquare/swan#the-processrunner-class
https://unosquare.github.io/swan/api/Unosquare.Swan.Components.ProcessRunner.html

**Comment by mariodivece** [comment]
This is now implemented in the latest commit. Reopen if the methods have issues or don't work.

**Comment by FrankDoersam** [comment]
Thank you for the fast and courteous support. The team is great!
