### ISSUE TITLE
Add RFID module support

### ISSUE THREAD

**Issue by robertsundstrom** [unosquare/raspberryio#30]
Add support for RFID modules that are using SPI for communication, such as RC522.

Code could simply be ported from C++, Python or Java. See here: https://github.com/maxpowel/RFID522

**Comment by geoperez** [comment]
Hi @robertsundstrom , thank you for the suggestion. We are not adding new features for now, but we are always open to new PRs.

**Comment by robertsundstrom** [comment]
OK. I did start implement it myself a while ago. Never got it to work and then stopped. I could upload it to GitHub and someone else could give me hints.

**Comment by geoperez** [comment]
Sure 👍

**Comment by robertsundstrom** [comment]
Great! I’ll do it tomorrow.

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robertsundstrom** [comment]
Here is my class: https://github.com/robertsundstrom/IotCamera/blob/develop/src/Components/MFRC522.cs

The program is here:
https://github.com/robertsundstrom/IotCamera/blob/develop/src/IotCamera/Program.cs

**Comment by geoperez** [comment]
Opening branch to integrate changes to Unosquare.RaspberryIO.Peripherals project.

**Comment by geoperez** [comment]
@robertsundstrom I was able to port your code, you can return multiples values with C# (are you a python dev?). Anyway, try to clone the repo at https://github.com/unosquare/raspberryio/tree/Issue30-AddRFIDModule

Then uncomment the following line to test:

https://github.com/unosquare/raspberryio/blob/Issue30-AddRFIDModule/src/Unosquare.RaspberryIO.Playground/Program.cs#L29

I don't have the hardware to test.

**Comment by robertsundstrom** [comment]
No. I’m a C# developer. I used ValueTuple and the new tuple syntax that is present in the latest stable version of the language. I see you switched them out for the old Tuple type. 

https://docs.microsoft.com/en-us/dotnet/csharp/tuples

Sure, I’ll try it.

**Comment by geoperez** [comment]
For a moment I think it was code ported from Python. We are using C# 7.1 for compatibility.

**Comment by robertsundstrom** [comment]
OK. ValueTuples are part of C# 7.1: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1

**Comment by geoperez** [comment]
Wow, I didn't know that. Maybe I didn't switch to 7.1 this project. Good to know 👍

**Comment by robertsundstrom** [comment]
👍

**Comment by robertsundstrom** [comment]
I should have written that it was a port FROM Java and Python.

**Comment by robertsundstrom** [comment]
I downloaded the code. Restored the thing with ValueTuples. 

Published the Playground code with SSHDeploy, and it does not invoke Tag(). It just exits the program.

**Comment by robertsundstrom** [comment]
Removed some of the stuff around (the Terminal stuff), and then I get the exception. I forgot to run as ```sudo```.

The Mfrc522Controller does not seem to work either.

**Comment by robertsundstrom** [comment]
I've tried various apps for reading card data with my setup. The ones written for NodeJS have failed. Anyway, If I follow this guide for Python it all works:

http://www.instructables.com/id/RFID-RC522-Raspberry-Pi/

I'm a novice when its comes to SPI, so I can't immediately spot the difference. I'll look into it more.

**Comment by robertsundstrom** [comment]
Found the problem:            

No command was sent in: (byte, int) Request(byte reqMode) 

```
WriteSpi(BitFramingReg, 0x07);
```

Method:

```
        public (byte, int) Request(byte reqMode)
        {
            var tagType = new List<byte> {reqMode};

            WriteSpi(BitFramingReg, 0x07); // THIS LINE

            var result = ToCard(PCD_TRANSCEIVE, tagType.ToArray());
            var status = result.Item1;
            var backBits = result.Item3;

            if ((status != MI_OK) | (backBits != 0x10))
            {
                status = MI_ERR;
            }

            return (status, backBits);
        }
```

**Comment by robertsundstrom** [comment]
My changes are in PR #31

**Comment by robertsundstrom** [comment]
What is the next step for this? Is there any additional changes in design or testing to be done?

**Comment by geoperez** [comment]
I will fix the Travis build and then merge. Should we release a peripherals
nuget?

**Comment by robertsundstrom** [comment]
@geoperez It would be great if you did. Thanks.

**Comment by robertsundstrom** [comment]
BW. This is my test project using ASP.NET Core: https://www.youtube.com/watch?v=s9pwgTyIoPg&t=10s&list=PLLBU--06ftFotvv3nwtm0dZxR-xu0i2-u&index=4

**Comment by geoperez** [comment]
Hey @robertsundstrom , we did some changes in the master branch. Can you try your RFID module again?

**Comment by robertsundstrom** [comment]
@geoperez Btw. Do you know why the libwiringpi DLL cannot be loaded when I run after having deployed? It does not seem to be extracted either. Is that because of the change?

**Comment by oldmanukko** [comment]
so so happy to see this is happening. i am new to electronics (2-3 days) and hope to get an RFID reader/writer going. i found C code and can follow that easy enough. but, would like to be able to stick to C# for now to get my project done. 

/following

**Comment by robertsundstrom** [comment]
@geoperez It does not work after the restructuring. It detects the card, but I cannot read the UID.

**Comment by robertsundstrom** [comment]
@oldmanukko I recommend you to have a look at this: https://github.com/robertsundstrom/dotnet-rpi-playground/blob/master/Services/Mfrc522Controller.cs

It is the original and it works

**Comment by oldmanukko** [comment]
@robertsundstrom thanks much! i will check it out.

**Comment by geoperez** [comment]
It's happening to us too. We didn't change anything in the resources class. After running the application, the second time it's working fine.

**Comment by geoperez** [comment]
@mariodivece 

"It does not work after the restructuring. It detects the card, but cannot read the UID."

**Comment by geoperez** [comment]
@robertsundstrom can you test my branch pre-0.14.0 and verify the embedded resources are extracted correctly? I can no longer reproduce it

**Comment by geoperez** [comment]
Issue #52
