### ISSUE TITLE
i2c add device typeinitialization exception

### ISSUE THREAD

**Issue by pmeloy** [unosquare/raspberryio#36]
Making my first attempt using this library and it's not going well. I don't know if its because of the lack of examples or if something is actually wrong.

Using VS2015 with Raspberry Pi3 and Raspbian Stretch with wiringpi enabled and RaspberryIO installed by Nuget two days ago.
My code:
`
using Unosquare.RaspberryIO;
.....
	class BMP180
	{
		public BMP180(int address)
		{
			try
			{
				var BMP180Device = Pi.I2C.AddDevice(address);
			}
			catch (Exception ex)
			{
				Console.WriteLine("Failed to register BMP180 at {0}. {1}", string.Format("{0:X2}", address), ex.GetType().FullName);
			}
		}
	}
`
And I get "Failed to register BMP180 at 77. System.TypeInitializationException"

I've been searching through all the documentation I can find and don't see anything else I should be doing.

P.S. Yes, i2cdetect shows the device at 77.

**Comment by geoperez** [comment]
Can you post the stacktrace?

**Comment by pmeloy** [comment]
System.TypeInitializationException: The type initializer for 'Unosquare.RaspberryIO.Pi' threw an exception. ---> System.TypeLoadException: Could not resolve type with token 01000043 (from typeref, class/assembly Unosquare.Swan.ReflectionExtensions, Unosquare.Swan, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null)
  at Unosquare.RaspberryIO.Pi..cctor () [0x0002e] in <24c16b38f03d4d8384ee43863d670a67>:0 
   --- End of inner exception stack trace ---
  at NexPi.BMP180..ctor (System.Int32 address) [0x00008] in <a4cc2f9a96f24eadb7b9a58e3f543101>:0 
  at NexPi.FrmMain.FrmMain_Load (System.Object sender, System.EventArgs e) [0x0006b] in <a4cc2f9a96f24eadb7b9a58e3f543101>:0 
  at System.Windows.Forms.Form.OnLoad (System.EventArgs e) [0x0001f] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) [0x00023] in <b0eb38f42f1041219336663febc755f3>:0

**Comment by pmeloy** [comment]
This would probably be self evident if I could run/debug from VS rather than build from VS then run from Pi.

**Comment by geoperez** [comment]
What version are you using? If you are using Unosquare.Raspberry.IO 0.13.0 please downgrade SWAN to 0.16.0.

**Comment by pmeloy** [comment]
Nuget on the RPi doesn't seem to have a way to list installed packages or a downgrade option or even an uninstall. Tried from VS and it seems to be doing things but it's still on the RPi.

Can't believe they'd have an RPi Nuget with no way to list or remove packages. Guess its time to wipe the SD card and start from scratch.

**Comment by pmeloy** [comment]
No good. It is IO 0.13 and Swan 0.16 but still the same error.

**Comment by geoperez** [comment]
Hello,

Try to update your nuget to version 0.14.0, please.

**Comment by geoperez** [comment]
@pmeloy ??
