### ISSUE TITLE
Add NetworkInfo Singleton

### ISSUE THREAD

**Issue by mariodivece** [unosquare/raspberryio#4]
NetworkInfo will contain a collection of NetworkAdapters
The ability to programmatically configure adapters (including wireless) will be exposed by this API

**Comment by FrankDoersam** [comment]
that would be fantastic!

**Comment by geoperez** [comment]
We already have some functionality in the [`NetworkSettings ` class](https://unosquare.github.io/raspberryio/api/Unosquare.RaspberryIO.Computer.NetworkSettings.html).

**Comment by FrankDoersam** [comment]
thank you!

**Comment by geoperez** [comment]
@mariodivece what else would you need?

**Comment by mariodivece** [comment]
I think we are good to go. CLosing!
