### ISSUE TITLE
Support remove_event_detect

### ISSUE THREAD

**Issue by forki** [unosquare/raspberryio#46]
Since you allow to register callbacks. can you please implement GPIO.remove_event_detect(port_number)?

**Comment by geoperez** [comment]
cc @mariodivece

**Comment by mariodivece** [comment]
I am looking at the code and I see no way of REMOVING the interrupt in WiringPi... Maybe a call to REPLACE the interrupt with an empty function would work?

**Comment by mariodivece** [comment]
I found this but it just feels "wrong"... https://www.raspberrypi.org/forums/viewtopic.php?t=41536
