### ISSUE TITLE
Add Bluetooth Singleton

### ISSUE THREAD

**Issue by mariodivece** [unosquare/raspberryio#5]
Enable bluetooth manipulation via the Pi API

**Comment by hidegh** [comment]
Just a question: why stick with singleton? Worst pattern to exist, especially with dependency injection. And on low level nothing prevents the user to create a global variable and or create custom static implementation with all the wiring needed - and store the result in a global variable...

I do understand that programming against one GPIO makes this static/singleton sound reasonable, but using static/singleton everywhere might limit possibilities (avail. via inheritance) in the long run.

**Comment by geoperez** [comment]
@hidegh the idea behind the singleton is just to keep a single entry point for that particular API. The API is not completed, but you can see something here:

https://github.com/unosquare/raspberryio/blob/Bluetooth/src/Unosquare.RaspberryIO/Bluetooth/BluetoothController.cs
