### ISSUE TITLE
Initialise GpioController with user selectable ControllerMode 

### ISSUE THREAD

**Issue by lawzla** [unosquare/raspberryio#50]
**Is your feature request related to a problem? Please describe.**
Would be beneficial to allow app to use GPIO without root permissions. For example GPIO control from a asp. net core application.

**Describe the solution you'd like**
Have the availability to set `ControllerMode.FileStreamWithHardwarePins` when  GpioController is initalised.

**Comment by geoperez** [comment]
You can run without root at [Version 0.16.0}(https://www.nuget.org/packages/Unosquare.Raspberry.IO/0.16.0).

**Comment by geoperez** [comment]
Closing.
