### ISSUE TITLE
Does this library support asp.net core 2.1?

### ISSUE THREAD

**Issue by Zeni241** [unosquare/raspberryio#57]
As I am getting bellow error as I reach sample code line in visual studio 2017. 
 ` var blinkingPin = Pi.Gpio[0];`
{System.TypeInitializationException: The type initializer for 'Unosquare.RaspberryIO.Pi' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.PlatformNotSupportedException: This library does not support the platform
   at Unosquare.RaspberryIO.Gpio.GpioController.Initialize(ControllerMode mode)
   at Unosquare.RaspberryIO.Gpio.GpioController..ctor()
   --- End of inner exception stack trace ---

**Comment by geoperez** [comment]
Hi, that's because you need to run your app as admin under Linux. What
environment are you using?

**Comment by Zeni241** [comment]
Hi
Thanks for reply. I am debugging the app in VS2017 on Windows 10. I want to put my app (along with this library) on raspberry Pi finally. Do I have to publish it there for this library to work?

**Comment by geoperez** [comment]
Yes, you need to publish and copy the folder to your raspberry pi. You
can't debug with Windows, we have no way to emulate hardware like GPIO
inside Windows.

**Comment by Zeni241** [comment]
Thanks a lot and good luck with your great work.
