### ISSUE TITLE
Move WiringPi wrappers to its own project and NuGet package

### ISSUE THREAD

**Issue by robertsundstrom** [unosquare/raspberryio#58]
I think that the WiringPi library wrappers should be placed in their own project and distributed as it's own NuGet package on which the actual RaspberryIO depends.

This would be great for those who would just want to use the wrapper.

Proposed package name: ```Unosquare.WiringPi```

**Comment by geoperez** [comment]
Any specific reason for that?

**Comment by robertsundstrom** [comment]
@geoperez, I later updated the issue by adding the reason:

This would be great for those who would just want to use the wrapper (pure WiringPi functions)

**Comment by geoperez** [comment]
We agree with that approach, in fact we are looking for support other
library (Pigpio https://github.com/unosquare/pigpio-dotnet). And the
ultimate goal is expose a public api to allow use any wrapper-connector,
but we have no enough time to achieve it right now.
