### ISSUE TITLE
Documentation for Peripheral Classes

### ISSUE THREAD

**Issue by TheSleepyPenguin** [unosquare/raspberryio#65]
Hi, I'd like to use the 'Button' peripheral class (I've installed the `Unosquare.RaspberryIO.Peripherals` package), but I'm not sure how to use it as I can't seem to find any documentation for it.
I'm new to C# so apologies if my question seems a bit simple...
Thanks for helping me out! :)

**Comment by geoperez** [comment]
Yeah, we don't have documentation for the peripherals yet. But the [Button source code](https://github.com/unosquare/raspberryio/blob/master/src/Unosquare.RaspberryIO.Peripherals/Button.cs) is really easy to read.

The class will initialize a button connected to a `GpioPin` and you need to set listeners to the events `Pressed` and `Released`. The Playground project has a [sample method](https://github.com/unosquare/raspberryio/blob/master/src/Unosquare.RaspberryIO.Playground/Program.Button.cs#L13) using a button (BCM Pin 26) to open a relay (BCM Pin 17)

```csharp
var relayChannel1 = Pi.Gpio.GetGpioPinByBcmPinNumber(17);
relayChannel1.PinMode = GpioPinDriveMode.Output;

var buttonPin = Pi.Gpio.GetGpioPinByBcmPinNumber(26);
buttonPin.PinMode = GpioPinDriveMode.Input;

var button = new Button(buttonPin);
button.Pressed += (s, e) => { "Pressed".Info(); };

button.Released += (s, e) =>
{
  "Released".Info();
  var value = relayChannel1.Read();
  relayChannel1.Write(!value);
};

Console.ReadKey();
```

**Comment by TheSleepyPenguin** [comment]
Thanks for the reply, I'll try it out!

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by TheSleepyPenguin** [comment]
@geoperez if you're asking me, then yes.

**Comment by geoperez** [comment]
Yes, closing.
