### ISSUE TITLE
Initial call to Pi.Spi fails with exception

### ISSUE THREAD

**Issue by TheOnlyRantis** [unosquare/raspberryio#75]
**Describe the bug**
Calling Pi.Spi.Channel0Frequency = Spi.MinFrequency results in an exception. The message from that exception is:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Unosquare.RaspberryIO.Pi' threw an exception.
  Source=Unosquare.RaspberryIO
  StackTrace:
   at Unosquare.RaspberryIO.Pi.get_Spi()
   at MAX31865..ctor(Int32 channel, Int32 chipSelect, Int32 readyPin, Byte config) in MAX31865.cs:line 91
   at AppFunctions..ctor(AppGlobal app) in AppFunctions.cs:line 81
   at AppGlobal..ctor() in AppGlobal.cs:line 18
   at App..ctor() in App.xaml.cs:line 33
   at Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in App.g.i.cs:line 24

Inner Exception 1:
MissingMethodException: Method not found: 'System.String Unosquare.Swan.Runtime.get_EntryAssemblyDirectory()'.

For background info I'm using Visual Studio 2017 and deploying to an RPi 3B.

**To Reproduce**
1. Download RaspberryIO nuget packages as described on "Installation" step of ReadMe
2. Add using statements in file
3. Add code to set Channel0 frequency for SPI bus as described above

**Expected behavior**
Get SPI bus and set the frequency of Channel 0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: Visual Studio 2017

**Hardware (please complete the following information):**
 - Device: Raspberry Pi 3B
 - OS: Windows IoT v1803

**Comment by geoperez** [comment]
What target framework are you using?

**Comment by TheOnlyRantis** [comment]
Universal Windows, specifically Windows 10 (IoT) version 1803 (10.0; Build 17134) which is using .NET Core

**Comment by k3z0** [comment]
Hi @TheOnlyRantis,

Could you please send us a sample code reproducing this behaviour?
