### ISSUE TITLE
Troubleshooting hardware error

### ISSUE THREAD

**Issue by skydivervrn** [unosquare/raspberryio#76]
Hi
I am using Visual Studio 2017, .Net 4.5.2, Unosquare.Raspberry.IO 0.17.2 and Unosquare.Swan 0.34.2, mono 4.6.2 and Raspbian 4.14.71.

After step "Run the project"(./Unosquare.RaspberryIO.Playground) I recived error bellow:

root@SH:/home/root/playground# mono Unosquare.RaspberryIO.Playground.exe
 00:07:23.715 INF >> Starting program at 03/11/2018 00:07:23
 00:07:23.937 INF >> GPIO Controller initialized successfully with 32 pins
 00:07:23.952 INF >> System Information
WiringPiVersion       : 2.46
RaspberryPiVersion    : Pi3ModelBSony
WiringPiBoardRevision : 2
ProcessorCount        : 4
InstalledRam          : 972234752
IsLittleEndian        : True
ModelName             : ARMv7 Processor rev 4 (v7l)
Features              : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CpuImplementer        : 0x41
CpuArchitecture       : 7
CpuVariant            : 0x0
CpuPart               : 0xd03
CpuRevision           : 4
Hardware              : BCM2835
Revision              : a02082
Serial                : 00000000da879820
UptimeTimeSpan        : 03:29:55.9000000
 00:07:23.954 INF >> Microseconds Since GPIO Setup: 89538
 00:07:23.955 INF >> Uname Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018
 00:07:23.961 INF >> HostName SH
 00:07:23.963 INF >> Uptime (seconds) 12595.91015625
 00:07:23.964 INF >> Uptime (timespan) 0 days 03:29:55
 00:07:24.274 INF >> Adapter:   eth0 | IPv4:                  | IPv6:                              | AP:                  | MAC:  b8:27:eb:87:98:20
 00:07:24.274 INF >> Adapter:     lo | IPv4:        127.0.0.1 | IPv6:                          ::1 | AP:                  | MAC:
 00:07:24.274 INF >> Adapter:  wlan0 | IPv4:     192.168.1.41 | IPv6:    | AP:                Z | MAC:  
 00:07:24.279 INF >> Testing RFID
 00:07:24.292 ERR >> [Main] Error
    $type           : Unosquare.RaspberryIO.Native.HardwareException
    ErrorCode       : 2
    Component       : SpiChannel.Channel1
    ExtendedMessage : No such file or directory
    Message         : A hardware exception occurred. Error Code: 2
    TargetSite      : Void Throw(System.String, System.String)
    StackTrace      :
        at Unosquare.RaspberryIO.Native.HardwareException.Throw (System.String className, System.String methodName) [0x00016] in <ab9595ff4ad442ee90085f742597ae35>:0
        at Unosquare.RaspberryIO.Gpio.SpiChannel..ctor (Unosquare.RaspberryIO.Gpio.SpiChannelNumber channel, System.Int32 frequency) [0x00074] in <ab9595ff4ad442ee90085f742597ae35>:0
        at Unosquare.RaspberryIO.Gpio.SpiChannel.Retrieve (Unosquare.RaspberryIO.Gpio.SpiChannelNumber channel, System.Int32 frequency) [0x00031] in <ab9595ff4ad442ee90085f742597ae35>:0
        at Unosquare.RaspberryIO.Gpio.SpiBus.get_Channel1 () [0x00021] in <ab9595ff4ad442ee90085f742597ae35>:0
        at Unosquare.RaspberryIO.Playground.Program.TestRfidController () [0x0001f] in <fdf8cb763a0647538d8c603e5c8a94b3>:0
        at Unosquare.RaspberryIO.Playground.Program.Main (System.String[] args) [0x00038] in <fdf8cb763a0647538d8c603e5c8a94b3>:0
    Source          : Unosquare.RaspberryIO
    HResult         : -2146233088
 00:07:24.552 INF >> Program finished.

Can you help me to fix this error?

**Comment by k3z0** [comment]
Hi @skydivervrn,

Maybe the reason is because you are running the RFID test and you don't have the required hardware. To fix this error you only need to comment line 40 in Program.cs:

```
   // TestRfidController();
```

Greetings.
