### ISSUE TITLE
i2c response wrong

### ISSUE THREAD

**Issue by sargin48** [unosquare/raspberryio#81]
**Describe the bug**
Arduino send "hello " text but you can see screenshot. 
Caming hhhhhhhh

**Screenshots**
<img width="758" alt="screen shot 2019-01-02 at 01 20 11" src="https://user-images.githubusercontent.com/3220540/50576894-ba645c00-0e2c-11e9-90f4-ade3b89e3bfb.png">
<img width="1335" alt="screen shot 2019-01-02 at 01 19 58" src="https://user-images.githubusercontent.com/3220540/50576895-ba645c00-0e2c-11e9-90fc-365e5f694b4b.png">

 - Version [0.17.2]

**Comment by k3z0** [comment]
Hi  @sargin48,

I think there are a misunderstanding in the code above:

`myDevice.Read()` does not read the available bytes in the buffer, instead reads one byte from the buffer. Therefore, the **104** that you are getting is not the buffer size, actually it is the ASCII value for char **'h'**, so the code is reading 104 times the same character.

By the moment we are using WiringPi as the underlying layer for interact with raspberry hardware. WiringPi is a high level solution and, thus, does not directly interact with the MCU, it uses, instead, the available Linux APIs. 

WiringPi does only support read one byte at the time (or a 16-bit word using `ReadAddressWord`). So, from the arduino code, the data must be sent one byte for each request.

In C# you can use `I2CDevice.Read(n)` that performs **n** reads to the underlying device to get the **n** required bytes as a byte array.

Here is an example of how can you accomplish what you want:

### C#
```csharp
var response = myDevice.Read(6);
var str = Encoding.ASCII.GetString(response);
Console.WriteLine($"Arduino Length: {response.Length} {str}");
```
### Arduino
```c
char data[ ] = "hello ";
byte reqIndex = 0;
// ...
void requestEvent()
{
   if (reqIndex == 6)
      reqIndex = 0;

   Wire.write(data[reqIndex++]);
}
```

**Comment by sargin48** [comment]
Hi Carlos Solorzano. Thanks alot alot alot alot alot :)
