### ISSUE TITLE
AM-2302 is not reporting decimal part of temperature

### ISSUE THREAD

**Issue by pkese** [unosquare/raspberryio#83]
There are a few issues with the AM-2302 sensor

- [ ] The sensor is reporting only integer values however HW sensor is capable of reporting decimal values as well (while other software is reporting 22.3 degrees, Unosquare is reporting only 22.0 degrees).

- [ ] There is unreasonable limitation of available IO pins. I have had the sensor installed on GPIO 0 and have tested it measuring temperatures just fine with some command line utility, however Unosquare wouldn't let me connect to GPIO 0, so I had to change wires to a different GPIO port. I don't understand why this limitation is necessary - it is certainly not a HW limitation.

- [ ] There is no way to disable constant polling of temperature. According to specs, the temperature sensor is heating itself up each time temperature measurement is taken, therefore in case of constant polling, the sensor itself may heat up and report higher temperatures that ambient. It would be nice to have an option to specify poll interval or even poll the sensor manually

- [ ] Occasionally, the sensor would report completely wrong values (it would be nice if the software would detect out-of-scope values cause by timing or read errors and retry the measurement).

**Comment by geoperez** [comment]
Hi @pkese, thanks for the head ups. We are kinda busy to fix these issues, but PR welcome.

**Comment by pkese** [comment]
@geoperez Sure... I may have a look when I can allocate some time.

One question though. It seems that there is some sort of a transition in the source code and that the actual package that's on Nuget does not quite match the master branch on GitHub. I think it is related to the Abstraction package work.

I'd like to start from a stable code base... Is there any ETA for the current master branch to be published to Nuget?

**Comment by k3z0** [comment]
Hi Peter,

As you notice we are making some changes to the source code, we are making a sort of abstraction for support any third party underlaying library with RaspberryIO. Currenly we only support [WiringPI](http://wiringpi.com/) and we have another [library](https://github.com/unosquare/pigpio-dotnet/) that supports [PiGpio](http://abyz.me.uk/rpi/pigpio/). So we are trying to make a base code that works with both libraries and even it let you make your own implementation for any other library.

Currently, we have another project that use [WiringPi](https://github.com/unosquare/wiringpi-dotnet) with the abstractions, and here are the corresponding nugets:

[Abstractions](https://www.nuget.org/packages/Unosquare.Raspberry.Abstractions/)
[WiringPi](https://www.nuget.org/packages/Unosquare.WiringPi/)

About your cuestions:
 - We notice that we use an integer value to perform the value division, so we are getting an integer result. We will fix this issue in future release. Or you can change the next line in source code:
   https://github.com/unosquare/raspberryio/blob/5a6e1195d640c4f8efadaafef739b44b8e95e148/src/Unosquare.RaspberryIO.Peripherals/TemperatureSensorAM2302.cs#L201

   Use this instead:
    ```csharp 
    temperatureCelsius: (sign * ((data[2] << 8) + data[3])) / 10m, 
    ```
 - We know that GPIO_0 and GPIO_1 hasn't any hardware limitation to perform Input/Output operations, nevertheless, this GPIOs are intended to be used for attaching compatible [ID EEPROM hats](https://github.com/raspberrypi/hats), so we intent to respect this constraint in our implementation.
 - The **TemperatureSensorAM2302** class is intended to be an easy to use/out of the box library, to quickly start using a AM2302 sensor. If you need a custom behavior you could use our implementation and make your own adjusments, you could share your solution with the community, maybe more people will find your solution useful for their own needs.

Greetings.

**Comment by pkese** [comment]
I've tried to test using the new codebase, but got

```
The type initializer for '<StartupCode$Server>.$Server.App' threw an exception. ---> System.TypeInitializationException: 
The type initializer for 'Unosquare.RaspberryIO.Pi' threw an exception. ---> 
System.InvalidOperationException: You need to load a valid assembly (WiringPi or PiGPIO)
   at Unosquare.RaspberryIO.Pi.ResolveDependency[T]() in d:\work\RPi\unosquare-raspberryio\src\Unosquare.RaspberryIO\Pi.cs:line 107
```

I'm now trying to figure out how what needs to be loaded...

**Comment by k3z0** [comment]
Are you usign the nuget packages or did you clone the RaspberryIO repository?

RaspberryIO only has abstractions, so you need to use the actually implementation. By the moment we only have the implementation for using [WiringPi](https://github.com/unosquare/wiringpi-dotnet). If you are using the WiringPi implementation and still have the error let me know to run some tests.

Greetings.

**Comment by pkese** [comment]
I cloned the RaspberryIO repository, because I wanted to add your fix for the AM2302.
I referenced RaspberryIO, Abstractions and Peripherials in my .csproj using `<ProjectReference Include="..."/>`  
I reverted any fiddling with PiGpio, so I'm now referencing the WiringPi (Nuget version) in my project, but I don't know how to explicitly initialize it for RaspberryIO.   
I'm still getting `You need to load a valid assembly (WiringPi or PiGPIO`

Thanks for all your help.

**Comment by k3z0** [comment]
@pkese 

We use a Dependency Container in order to load all needed classes, if you have all needed references in your project, all of them should be loaded. Let me run some tests to confirm that the Dependency Container is working properly.

**Comment by k3z0** [comment]
Hi @pkese,

We just release some fixes to RaspberryIO, Peripherals and WiringPi. Just pull the last repository changes, update WiringPi to the last nuget version ([0.2.3](https://www.nuget.org/packages/Unosquare.WiringPi/0.2.3)) and run some tests.

Currently we don't have a AM2302 sensor, so we couldn't perform the tests by ourselves, so We will be waiting for feedback from you.

Thanks.

**Comment by k3z0** [comment]
I almost forget it, for properly bootstrap RaspberryIO you must add this line of code:

```csharp
Pi.Init<BootstrapWiringPi>();
```

**Comment by pkese** [comment]
Hi @k3z0 

I've tested the new code and I can now properly bootstrap the library.

The line 

https://github.com/unosquare/raspberryio/blob/848fb2c12b735a782097d323d073ca24f5ff3799/src/Unosquare.RaspberryIO.Peripherals/TemperatureSensorAM2302.cs#L187

should actually remain summed with `+` just as before:

```csharp
var checkSum = data[0] + data[1] + data[2] + data[3];
```

Without changing `|` into `+` nothing really works,  
whereas after the fix, now checksum validation works correctly and I don't get any failed reads anymore.

Just a quick note:

I did waste a lot of time figuring out that `WiringPI` had been renamed to `WiringPi` and that pin numbering changed from WiringPi's to Broadcom Gpio numbering scheme. It was a trivial fix, but really hard to find out and thus took me a long time to fix.

It would be really nice to inform people of these two changes in some sort of README or CHANGELOG file.

**Comment by k3z0** [comment]
Hi @pkese 

We already fix the checksum line as it was previously, sorry about that, we test with another sensor and it only worked using "or" instead of sum, thats why I asked you to test using the correct sensor.

We still working on the Abstractions project and its implementations (like PiGpio), thats why we doesn't have the release notes yet. 

We appreciate that you are already using this changes, your feedback is very important for us and we are going to take into account all your comments for future release notes.

Thanks.

**Comment by geoperez** [comment]
Can we close this issue?

**Comment by pkese** [comment]
Sure
