### ISSUE TITLE
Unregister interrupt callbacks on GPIO Pins

### ISSUE THREAD

**Issue by Fuzzygaro** [unosquare/raspberryio#87]
I need the ability to update GPIO configuration at runtime based on commands from a supervisor process. Some pins are set up with interrupts but the pins to detect events on may change. As such I need to be able to unregister interrupt callbacks. As it stands I will have to restart the application to configure new pins with callbacks.

**Comment by jifka** [comment]
I'd love for this to be re-opened. To not have a way to unregister a callback is a little sloppy. If you build an interface to the GPIO pins, you should have a way to clean up after yourself or selectively register an interrupt and unregister if you change the pin mode to output. I've found that you can't register an interrupt on an output pin, but you can change the mode to input, register, and then change to output and you still get callbacks firing.
