### ISSUE TITLE
Add support for the Compute Module 3 to the PiVersion enum

### ISSUE THREAD

**Issue by foxton33** [unosquare/raspberryio#88]
Hi - I like the raspberryIO and I'm using it with the Compute Module 3.
Could you add support for the Compute Module 3 (CM3)?

I believe you just need to update the enum Unosquare.RaspberryIO.Computer.PiVersion
and add the entry:

/// <summary>
/// The Compute Module 3
/// </summary>
ComputeModule3 = 0xa220a0,

Thanks

**Comment by k3z0** [comment]
Hi @foxton33 

We already updated PiVersion enum including all the available models from [Pi documentation](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md).

Thanks.

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by foxton33** [comment]
Thanks @k3z0 and @geoperez !
