### ISSUE TITLE
Support new-style Revision codes

### ISSUE THREAD

**Issue by k3z0** [unosquare/raspberryio#90]
Add fields to support the new-style revision codes:

**uuuuuuuuFMMMCCCCPPPPTTTTTTTTRRRR**

| Part | Represents |
| :---- | :--- |
| uuuuuuuu | Unused |
| F | New flag |
| MMM | Memory size |
| CCCC | Manufacturer |
| PPPP | Processor |
| TTTTTTTT | Type |
| RRRR | Revision |

#### Reference
[Raspberry Pi revision codes](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md)

**Comment by geoperez** [comment]
Status?
