### ISSUE TITLE
Standard Web Camera

### ISSUE THREAD

**Issue by IvayloIL** [unosquare/raspberryio#91]
As we know RPI and raspbian support using an external standard web camera connected via USB ports. It will be awesome if you support this as well aside with the regular Camera module. 

- https://www.raspberrypi.org/documentation/usage/webcams/README.md

**Comment by k3z0** [comment]
Hi @IvayloIL 

At this moment it is not a priority for us to adding support for USB cameras directly through RaspberryIO, nevertheless, you can use a project like [OpenCvSharp](https://github.com/shimat/opencvsharp) to achieve your goal.

Another approach you could try is, based in our [camera classes](https://github.com/unosquare/raspberryio/tree/master/src/Unosquare.RaspberryIO/Camera), try to implement your own wrapper for **fswebcam**. Although this sounds more complicated you could start by implementing only the commands you need to take a photo and then try to make a full API. Take a look to our code, you'll see is not that difficult.
