### ISSUE TITLE
Add support for multiple pinout numbering systems

### ISSUE THREAD

**Issue by k3z0** [unosquare/raspberryio#99]
`RaspberryIO.Abstractions` only support the BCM pinout numbering system, independently of the actual implementation used (WiringPi, PiGpio or any other).

It would be a nice feature that the user could choose the pinout numbering system of his preference in the bootstrap process.

**Comment by TylerLeonhardt** [comment]
Thanks @k3z0! We rely on raspberryio in [PowerShell-IoT](https://github.com/PowerShell/PowerShell-IoT). It would be great to have this so we don't have to introduce a breaking change for our customers!
